---
Framework: "serviceweaverkube"
SSH:
  user: root
  port: 22
ServiceWeaverConf:
  service_name: "<service_name>"
  kubectl_config_path: "<kubectl_config_path>"
  jump_clinet_host: "<gateway_service_ip>"
  jump_client_port: 2222
  jump_client_user: "root"
  jump_client_password: "password123"
  jump_client_key_path: ""
PrerunGdbCommands:
  - name: "load extension"
    command: "source /workspace/extension.py"
Conf:
  log_dir: "YOUR_LOG_DIR"
  base_dir: "YOUR_BASE_DIR"
  api_server_port: 5000